language: cpp
git:
  depth: false
services:
  - docker
matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 CXXFLAGS='-Wall -B/usr/lib/gcc/x86_64-linux-gnu/7' && SONAR=false"
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 CXXFLAGS='-Wall -B/usr/lib/gcc/x86_64-linux-gnu/7' && SONAR=false"
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 CXXFLAGS='-Wall' && SONAR=false"
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 CXXFLAGS='-Wall' && SONAR=true"
      addons:
        sonarcloud:
          organization: "thoriumlang"
          token:
            secure: $SONARQUBE_TOKEN
before_script:
  - eval "${MATRIX_EVAL}"
  - env | grep -v SONARQUBE_TOKEN
script:
  - |
    docker run --rm -it \
      -v `pwd`:/sources:ro \
      -v `pwd`/bw-output:/bw-output \
      -e CC="$CC" \
      -e CXX="$CXX" \
      -e CXXFLAGS="$CXXFLAGS" \
      -e SONAR="$SONAR" \
      cpollet/cpp
  - |
    if [ "$SONAR" = "true" ]; then
      sonar-scanner -Dproject.settings=sonar.properties
    fi